Icon for Avocode
numixproject/numix-core pull request #3476
Opened 2016-11-05 23:49 UTC by Jacajack

Icon for Avocode as requested in https://github.com/numixproject/numix-core/issues/3317

2016-11-06 09:52 UTC, Foggalong commented
I know you're just sticking to the original icon, but we generally avoid gradients like this in icons because it goes against our design guidelines. In this situation I'd probably recommend using a darker green for the background gradient and then a solid light green for the symbol, taking both colours from the gradient in the original icon if possible.

2016-11-06 09:56 UTC, Jacajack commented
Sure, give me a second :)

2016-11-06 10:12 UTC, Jacajack commented
![image](https://cloud.githubusercontent.com/assets/6173262/20036761/681cd684-a411-11e6-97cc-5bdb88153598.png)![selection_006](https://cloud.githubusercontent.com/assets/6173262/20036772/c4bae016-a411-11e6-8788-8cefc8f46cce.png)

I made two version of the icons with swapped colors (I can tweak them a bit If you like). Which one do you prefer?

2016-11-06 15:28 UTC, Foggalong commented
I think definitely no gradients and colourful background is the way to go, but maybe we could tweak the symbol a bit so it resembles an avocado a bit more? Something like this  
![screenshot_2016-11-06_15-27-09](https://cloud.githubusercontent.com/assets/5920259/20039054/8f16189e-a435-11e6-9581-7b57f350f3de.png)

If you're not up for that just let me know and I'll do the tweaking :+1:

2016-11-06 19:47 UTC, Jacajack commented
![selection_999 036](https://cloud.githubusercontent.com/assets/6173262/20041004/32df8e48-a462-11e6-816c-b4e870194c4d.png)

Something like this?

2016-11-06 20:36 UTC, Foggalong commented
@Jacajack That, with then a slightly smaller version of the outer egg part coloured yellow layered above the light green. Then add a shadow like the main symbol shadow for the stone against the yellow

2016-11-06 20:56 UTC, Jacajack commented
![selection_999 042](https://cloud.githubusercontent.com/assets/6173262/20041556/609c4cd2-a46b-11e6-8357-3b1e4eab25fb.png)

Yeah, that's a real avocado now. At first I wanted the icon to look more or less like the original one, but I like that. :)

2016-11-06 20:57 UTC, Foggalong commented
That's looking great! Push that and then I'll do one last code checkover before merging :)

2016-11-06 21:06 UTC, Jacajack commented
If you ever need an egg icon, remember about me :stuck_out_tongue_closed_eyes: 
![selection_999 043](https://cloud.githubusercontent.com/assets/6173262/20041691/474ff5b0-a46d-11e6-9fc9-6991dd4b4cf4.png)

2016-11-06 21:29 UTC, Foggalong requested changes
Excellent, last few nit picky changes now just based on the SVG content rather than the iconography.
- [ ] Increase the size of the light green egg to 20px by 26px with location (14,11). Our standard symbol size is 24px by 24px so this is a nice compromise. Remember to move & resize the background shadow accordingly.
- [ ] Increase yellow eggs size to 18px by 24px with location (15,12). This just keeps everything grid aligned.
- [ ] Same with the stone, increase to 10px by 13px with location (10,15). Remember to keep the shadow for the stone 1px to the right and 1px down, the one pushed is slightly closer than that.
- [ ] When saving the file, save as "Optimised SVG". This means it takes up less file space in packaging but keeps the exact same design

With those done this is good to go :+1:

2016-11-06 21:29 UTC, Foggalong requested changes

2016-11-06 21:29 UTC, Foggalong commented on data.json
> +	"avocode": {
This also has the thing with the tap instead of a space :stuck_out_tongue:

2016-11-06 21:41 UTC, Jacajack commented
![untitled window_999](https://cloud.githubusercontent.com/assets/6173262/20041982/160678f8-a472-11e6-9915-400487f0b7b6.png)

Inkscape throws an error when I'm trying to save as optimised SVG. :confused:
Can I use `svgo` or something like this?

2016-11-07 08:25 UTC, Jacajack commented
After manually retyping some Python, I fixed that. I hope everything is alright :stuck_out_tongue:

2016-11-07 10:19 UTC, Foggalong commented
Yeah, it can be a bit messy with that. Thanks for powering through the errors though :)

2016-11-07 10:20 UTC, Foggalong approved these changes

2016-11-07 10:20 UTC, merged