Icon for Fuse ZX Spectrum Emulator
numixproject/numix-core pull request #3477
Opened 2016-11-06 00:56 UTC by Jacajack

![image](https://cloud.githubusercontent.com/assets/6173262/20034611/01366874-a3c4-11e6-903e-0163521cbc0e.png)

Icon for Fuse Emulator as requested in https://github.com/numixproject/numix-core/issues/3315.
I'm not sure if shadow located under the rainbow is necessary.

2016-11-06 10:00 UTC, Foggalong requested changes
The design is nice, but it could be made more consistent with our design guidelines by cropping and centring the logo (and possibly reducing the angle toward the vertical too) like it's displayed on this machine.

![](http://www.web8bits.com/Marcas/Sinclair/graficos/Spectrum_128_espanhol.jpg)

2016-11-06 10:00 UTC, Foggalong commented on data.json
> +	"fuse-emulator": {
There's on indent too far here. It's not a big deal but it breaks consistency

2016-11-06 10:03 UTC, Jacajack commented on data.json
> +	"fuse-emulator": {
Weird... It looks alright in gedit... :confused:

2016-11-06 10:06 UTC, Foggalong commented on data.json
> +	"fuse-emulator": {
The `data.json` uses spaces rather than tabs, but this line in your commit uses tabs instead. None of the other lines you've committed do though :stuck_out_tongue:

2016-11-06 10:33 UTC, Jacajack commented
@Foggalong Again, I have two variations.

![selection_008](https://cloud.githubusercontent.com/assets/6173262/20036863/9fb04a42-a414-11e6-9b81-ad2424ec0cc4.png)![selection_007](https://cloud.githubusercontent.com/assets/6173262/20036864/a0f695a0-a414-11e6-8c93-e4d9c326b945.png)

I think the first one looks little bit sharper.

2016-11-06 15:29 UTC, Foggalong approved these changes

2016-11-06 15:29 UTC, Foggalong requested changes
The isolated symbol with the gaps between the lines (option 1) looks much better. Maybe reduce the angle ever so slightly more though? Then you might be able to get away with a slightly larger symbol (up to 26px^2)

2016-11-06 20:46 UTC, Jacajack commented
I managed to make the stripes wider and more sloped. Square symbols don't really look good in this case (at least I think so), so I made rectangular ones:

26x19:
![selection_999 041](https://cloud.githubusercontent.com/assets/6173262/20041468/cc80bd54-a469-11e6-9a38-f57974b8aa0e.png)

24x17:
![selection_999 040](https://cloud.githubusercontent.com/assets/6173262/20041470/cf195076-a469-11e6-81a4-245acafdb25f.png)

2016-11-06 20:58 UTC, Foggalong commented
26x19 looks great! Push that and I'll merge :)

2016-11-06 21:32 UTC, Foggalong requested changes
This all looks good to me, just needs saving as an optimised SVG and we're good to go :+1:

2016-11-07 10:18 UTC, Foggalong approved these changes

2016-11-07 10:18 UTC, merged