Remove .png symlinks
numixproject/numix-core pull request #3485
Opened 2016-11-07 20:39 UTC by bil-elmoussaoui

.png icons are hardcoded and shouldn't be symlinked. The icons must be fixed manually or using hardcode fixer instead.

2016-11-07 20:51 UTC, Foggalong requested changes

2016-11-07 20:51 UTC, Foggalong commented on data.json
> -    "grsync.png": {
Because this is a root icon, you'll also have to switch the root icon name around too (for Circle and Square)

2016-11-07 20:52 UTC, bilelmoussaoui commented on data.json
> -    "grsync.png": {
Forgot that! i will do in few minutes

2016-11-07 20:59 UTC, bil-elmoussaoui commented
Done! For square, there was a png and an svg icon, so i just removed the png file. Should be ready to go

2016-11-07 21:09 UTC, Foggalong commented on icons/square/48/grsync.png.svg
> -<svg viewBox="0 0 48 48"><defs><linearGradient id="linearGradient3764" x1="1" x2="47" gradientUnits="userSpaceOnUse" gradientTransform="translate(-48.000001,0.00221467)"><stop stop-color="#5d873f" st
You deleted the wrong file! The one left uses the Square legacy design. I'm not sure why there was a discrepancy between the two though

2016-11-09 20:07 UTC, Foggalong commented
@bil-elmoussaoui?

2016-11-09 20:10 UTC, bil-elmoussaoui commented
Which ones should i keep https://github.com/numixproject/numix-core/blob/master/icons/square/48/grsync.svg or https://github.com/numixproject/numix-core/blob/master/icons/square/48/grsync.png.svg?

2016-11-09 20:13 UTC, Foggalong commented
[This one](https://github.com/numixproject/numix-core/blob/master/icons/square/48/grsync.png.svg) but change the name to remove the extension. It doesn't display properly in some environments but it's at least using the up to date design which is preferable.

2016-11-09 20:17 UTC, bil-elmoussaoui commented
Done

2016-11-09 22:04 UTC, Foggalong approved these changes

2016-11-09 22:04 UTC, merged