Icons for CINEMA 4D
numixproject/numix-core pull request #3522
Opened 2016-12-10 18:48 UTC by really-need-an-api-key

Icon for [CINEMA 4D](https://www.maxon.net/en/products/cinema-4d/overview/), a 3D modelling package.
![c4d_logo](https://cloud.githubusercontent.com/assets/11636003/21075368/6718c5bc-bf10-11e6-9445-6ef20761dd0e.png)
![screenshot from 2016-12-10 19-39-59](https://cloud.githubusercontent.com/assets/11636003/21075376/8727a562-bf10-11e6-84cc-9497df0b8915.png)

It's actually a Windows program, but works pretty well under Wine.
However, the names of the icons (`9FD2_Commandline.0`, `38F9_CINEMA 4D TeamRender Server.0`, `60EE_CINEMA 4D.0`, `F879_CINEMA 4D TeamRender Client.0`) Wine creates have spaces in them, so they would cause the icon cache to be invalid.
I wasn't sure whether to use them, so didn't and opted for a neutral `cinema4d` filename, but I don't know if that's right.

2016-12-19 18:01 UTC, palob commented
Symbol size shouldn't exceed 26x26 or 28x28.

Maybe it could work as full baseplate design or on a 30x30 circle (similiar to what you did for Square).

You shouldn't do something like this
![cinema4d-1](https://cloud.githubusercontent.com/assets/7050624/21323320/1b716ad8-c61d-11e6-9aba-05e55b035f9d.png)

It's better to substract that thing from the blue shape. There's even more strange stuff going on in your Square icon, causing a jagged outline around the white circle.

2017-01-30 20:59 UTC, really-need-an-api-key commented
I haven't abandoned these two open PRs yet. Unfortunately I was a little busy lately, but I'll get to them soon.

2017-04-05 14:23 UTC, Foggalong requested changes
As @palob said, symbol size needs reducing

2017-12-24 14:28 UTC, Foggalong approved these changes

2017-12-24 14:30 UTC, merged