Icons for Skifra
numixproject/numix-core pull request #3560
Opened 2017-01-21 14:52 UTC by palob

https://github.com/Skrifa/Skrifa

![skrifa-128](https://cloud.githubusercontent.com/assets/7050624/22175248/a1e2efa4-dff1-11e6-98df-92043e0ebc4e.png)

![skifra-numix](https://cloud.githubusercontent.com/assets/7050624/22175250/a49b2658-dff1-11e6-9cdb-dcde58587cf7.png)

2017-01-25 16:56 UTC, Foggalong requested changes
With the yellow as is there isn't enough contrast between the baseplate and the icon. Try either a darker yellow or an alt colour for the baseplate.

2017-01-25 20:06 UTC, palob commented
Here's a darker yellow.
![skifra0](https://cloud.githubusercontent.com/assets/7050624/22307110/19b5a5dc-e342-11e6-8e6a-824112e04210.png)

2017-01-26 16:17 UTC, Foggalong approved these changes

2017-01-26 16:17 UTC, merged

2017-01-26 16:18 UTC, Foggalong commented
I messed up there, really sorry about that - thought the change had already been pushed when it wasn't :P