Layout Editor (3D and Text Editor)
numixproject/numix-core pull request #3582
Opened 2017-02-04 17:29 UTC by leoheck

2017-03-11 20:31 UTC, leoheck commented
@palob, is this icon good to go or I have to make something else?

2017-03-15 21:14 UTC, palob commented
The icons do work for smaller sizes now but the symbol is spread over too much of the baseplate. Symbol size is about 31px X 33px which is definitely too much of a stretch. Moreover the **3D** and **TE** typeface objects need to be converted into paths.

You need to get the symbol smaller. Maybe it's better to drop the text-only design altogether and find more creative metaphors for "text editor" and "3D".

2017-03-16 00:40 UTC, leoheck commented
Ok, what I have to do? Reduce the height, width or both? What is the maximum (tolerable) symbol size?

I like to have creative metaphors as you said, but I think it is nice to approach the author's intent. In this way, I have to think in an improvement.

2017-03-16 21:06 UTC, palob commented
26x26 (28x28) for non spherical symbols, 30x30 for speherical ones.

2017-04-05 14:17 UTC, Foggalong requested changes
As @palob said, symbol size needs reducing.

2017-04-19 22:17 UTC, palob commented
Smaller now but you need to tinker with the positioning. The letters aren't crisp enough and the what is supposed to be an **L** is not recognisable as such.

2018-03-13 15:42 UTC, Foggalong commented
@palob You fancy having a look at this? Just realised it's coming up for a year since the last update

2018-03-13 21:22 UTC, palob commented
I can give this a shot. I envisage slightly 3Dfying the current ``layout`` icon.

2018-03-15 22:42 UTC, palob commented
No idea for the text editor one though.

2018-04-01 20:38 UTC, palob commented
Hmm, doesn't mix well with how we do shadows.

![layout3d](https://user-images.githubusercontent.com/7050624/38177199-574aa154-35fd-11e8-98ef-8ee16fb79b65.png)

2018-04-04 22:52 UTC, Foggalong commented
Yeah it's not a great original to work with :confused:

2018-04-05 12:32 UTC, leoheck commented
Haha, sure it is not original. It was a draft idea to put some icon on that app because the icon which came with de app sucks. I never thought it was going to take a year to move this thing forward. If you guys have a better idea, just use it. Actually, I like most when the icon recall the original idea (with colors or shape or symbol) of the app creators.

2018-04-05 14:31 UTC, Foggalong commented
@leoheck No worries, these things can be hard to get right. @palob It might be worth deviating from it entirely and just using some iconography related to the apps purpose instead.

2020-07-04 14:33 UTC, creepertron95 commented
@Foggalong This issue has not been touched for 2 years. I have some ideas for Layout Editor 3D and Text Editor:

- Layout Editor 3D : Have a cube with the Letters L and E on the faces of the cube

- Layout Editor Text Editor : Have a notepad symbol with the Layout Editor Logo on it.

2020-07-04 16:41 UTC, palob commented
Yeah, the cube might do it!

2026-02-21 01:25 UTC, leoheck commented
🤡

2026-02-21 01:25 UTC, closed without merging