Icon for Icemon
numixproject/numix-core pull request #3638
Opened 2017-04-09 16:47 UTC by palob

https://github.com/icecc/icemon

![hi128-app-icemon](https://cloud.githubusercontent.com/assets/7050624/24839110/f1569158-1d54-11e7-9bcc-c0deb1c8114f.png)

![icemon-numix](https://cloud.githubusercontent.com/assets/7050624/24839112/f4adaaf8-1d54-11e7-88fc-9d01fc46bf0b.png)

2017-04-12 08:08 UTC, Foggalong requested changes
The contrast between the yellow circle and cream background isn't really high enough. Fixing this might involve finding a different background colour because I think changing the yellow to work might necessitate it be brown.

2017-04-12 23:00 UTC, palob commented
One of these?
![icemon](https://cloud.githubusercontent.com/assets/7050624/24982977/873029dc-1fe4-11e7-9fce-2c0b3a9cc7a5.png)

2017-04-14 15:01 UTC, Foggalong commented
0 works well :+1:

2017-04-19 20:19 UTC, Foggalong approved these changes

2017-04-19 20:19 UTC, merged