Square icon for Kodi
numixproject/numix-core pull request #3678
Opened 2017-04-19 18:22 UTC by MrTimscampi

Part of numixproject/numix-core#3481

I resized the symbol to fit into the circular symbol guide, as I thought it looked better than fit to the square symbol guide (It looked to small).

2017-04-19 18:30 UTC, palob requested changes
The vertical lines aren't in line with the grid. As for the bigger size, please transform the symbol to a full 30x30 instead of 29.something px.

2017-04-19 18:30 UTC, palob commented
![kodi](https://cloud.githubusercontent.com/assets/7050624/25195796/05ca4ea8-253f-11e7-844e-2d32aefcd38d.png)

2017-04-20 10:14 UTC, MrTimscampi commented
For consistency's sake, I reverted the icon size (The geometry would have to change a bit for the resizing, which isn't really optimal).

I also added the 10L gradient on the baseplate since, apparently, it's missing from the square template and I hadn't noticed (I'll make a pull request to fix all my previous square icons after this).

2017-04-20 19:41 UTC, palob commented
Thanks for the fixing.

2017-04-20 19:41 UTC, palob approved these changes

2017-04-21 08:50 UTC, merged