[Square] Gnome Books
numixproject/numix-core pull request #3685
Opened 2017-04-20 08:53 UTC by bil-elmoussaoui

Part of #3481 
![gnome-books](https://cloud.githubusercontent.com/assets/7660997/25222030/89a82c7c-25b7-11e7-8b29-7339b32f1a6b.png)

2017-04-20 19:29 UTC, palob commented
Needs a gradient, otherwise it's fine.

2017-04-22 18:26 UTC, palob requested changes
As with your other icons the gradient is bottom up :)

2017-04-30 12:03 UTC, palob approved these changes

2017-05-17 20:41 UTC, Foggalong approved these changes

2017-05-17 20:41 UTC, merged