few square icons
numixproject/numix-core pull request #3703
Opened 2017-04-29 22:04 UTC by bil-elmoussaoui

Few square icons for #3481 
The PR includes : 
- [ ] discord
- [ ] terminix 
- [ ] webtorrent-desktop
- [ ] gnome-todo

2017-04-30 12:16 UTC, palob requested changes
For the webtorrent icon, symbol position should be Y11 (and Y10 for the shadow respectively).

2017-05-17 20:55 UTC, bil-elmoussaoui commented
@palob should be fixed now, sorry for the long delay

2017-06-04 12:06 UTC, bil-elmoussaoui commented
@palob can you take a look at this one?:)

2017-06-04 12:56 UTC, palob approved these changes

2017-07-07 18:47 UTC, merged