Icon for Reigns (Steam)
numixproject/numix-core pull request #3726
Opened 2017-05-20 13:06 UTC by matemeszaros

| Original icon | Circle icon | Square icon |
| --- | :--: | :--: |
|  ![original reigns](https://cloud.githubusercontent.com/assets/15245298/26275969/62711d8a-3d6d-11e7-939c-023ba9b9d7c6.png) | ![reigns circle](https://cloud.githubusercontent.com/assets/15245298/26275986/c383657e-3d6d-11e7-8aa0-3158e313c2e2.png) | ![reigns square](https://cloud.githubusercontent.com/assets/15245298/26275990/dd4d02bc-3d6d-11e7-9f3e-cd2ae9911460.png) |

2017-05-20 15:57 UTC, matemeszaros commented
The symbols were clearly too big, so i shrunk them a bit:

| Circle icon | Square icon |
| :--: | :--: |
| ![reigns circle](https://cloud.githubusercontent.com/assets/15245298/26277265/7b402fd2-3d85-11e7-8951-ef43962a17b2.png) | ![reigns square](https://cloud.githubusercontent.com/assets/15245298/26277272/8227cc10-3d85-11e7-84bd-cc1fd4a218a9.png) |

2017-05-21 21:42 UTC, palob requested changes
It's a cool design but I think it could still be samller. You can get the symbol height down to 28px by shortening the merlon things by 1px, slimming down the "castellation base band" to 4px height and shortening the dower base by 1px.
There's some strange inner paths in the 2 yellow castellation paths you can get rid of by performing a path union on each path itself.

2017-05-22 21:55 UTC, palob commented
Size is fixed but there's still the inner paths (same for the shadow).
![innerpath](https://cloud.githubusercontent.com/assets/7050624/26329984/17760d52-3f4a-11e7-863c-651025f8f8c2.png)

2017-05-24 06:16 UTC, palob approved these changes

2017-07-07 18:46 UTC, merged