Big Pharma
numixproject/numix-core pull request #3735
Opened 2017-05-30 05:18 UTC by W-Floyd

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  ![original](https://cloud.githubusercontent.com/assets/11786132/26568447/c7fd1e16-4546-11e7-904d-34e825d4c54a.png) |  ![circle](https://cloud.githubusercontent.com/assets/11786132/26568966/c7d29a2a-454a-11e7-8d41-f502cefff7c8.png) | ![square](https://cloud.githubusercontent.com/assets/11786132/26568982/ee5871ec-454a-11e7-8753-9121c94af78b.png) |

2017-06-02 21:43 UTC, palob commented
The symbol design is nice yet too big. Can you shrinkt the icon down to a height of 24px, 26px (or 28px)?

2017-06-02 21:44 UTC, W-Floyd commented
Yup, had thought that'd need to happen. I'll get onto it later today.

2017-06-03 06:40 UTC, W-Floyd commented
Before and after:
![image](https://cloud.githubusercontent.com/assets/11786132/26751294/4b2769ce-4879-11e7-88a0-270121ece9b3.png)

2017-06-03 06:59 UTC, palob commented
What's the new size?

2017-06-03 07:01 UTC, W-Floyd commented
26 ish pixels high (because the outline of the beaker is a stroke at present, the corner bumps it out a bit)

2017-06-03 07:07 UTC, palob commented
Alright, if all vertical lines are aligned to the grid and the strokes are converted to paths it's good to go.

You need to reopen this PR without any merged commits before we can merge it though.
(It's not enough to revert the commits and reapply them, there must not be any in the git history. Otherwise buggy Launchpad will break the PPA.)

2017-06-03 07:10 UTC, W-Floyd commented
Okay, I'll convert the strokes then.
I won't pretend to be that good in git, but would re-writing history work? I'm happy to re-open, just curious.

2017-06-03 07:13 UTC, palob commented
Re-writing is OK, in case no trace is left. We had to do this in the past.

2017-06-03 07:14 UTC, W-Floyd commented
Okay, I'll give that a go.

2017-06-03 08:54 UTC, W-Floyd commented
Here's the updated version, I believe the commit history is okay now.
![image](https://cloud.githubusercontent.com/assets/11786132/26752209/e580d5dc-488d-11e7-8ae9-7d0f1f7dbe5e.png) 
![image](https://cloud.githubusercontent.com/assets/11786132/26752213/f822dd34-488d-11e7-948c-4cf915135fc3.png)

2017-06-21 23:37 UTC, W-Floyd commented
![iconified_steam_icon_344850](https://user-images.githubusercontent.com/11786132/27410966-5856dada-572e-11e7-91bc-dbe6c3458c02.png)

2017-06-22 08:28 UTC, palob approved these changes

2017-06-22 08:30 UTC, palob commented on icons/circle/48/steam_icon_344850.svg
> +  <path d="m20 10.586l-1.4141 1.4141 0.70703 0.70703 1.707 1.707v7.4121l-5.4199 15.174h18.84l-5.4199-15.174v-7.4121l1.707-1.707 0.70703-0.70703-1.4141-1.4141-0.70703 0.70703-2.293 2.293v8.5879l4.582
There's some strange stuff here. Can you please save the files again?

2017-06-22 08:33 UTC, W-Floyd commented on icons/circle/48/steam_icon_344850.svg
> +  <path d="m20 10.586l-1.4141 1.4141 0.70703 0.70703 1.707 1.707v7.4121l-5.4199 15.174h18.84l-5.4199-15.174v-7.4121l1.707-1.707 0.70703-0.70703-1.4141-1.4141-0.70703 0.70703-2.293 2.293v8.5879l4.582
Tried just now, didn't change that section... I'll see if there's anything weird going on that I can find.

2017-06-22 08:39 UTC, W-Floyd commented
Still looks the same, but I think that takes care of the weirdness.

2017-06-22 08:46 UTC, palob requested changes
Theres still strange paths, e.g. 
```xml
<path d="m20 10.586-1.4141 1.4141 2.414 2.414v7.4121l-5.4199 15.174h18.84l-5.4199-15.174v-7.4121l2.414-2.414-1.4141-1.4141-3 3v8.5879l4.582 12.826h-13.164l4.582-12.826v-8.5879zm3.8574 14.414-2.8574 8h8l-2.8574-8z" dominant-baseline="auto" style="color-rendering:auto;color:#000000;dominant-baseline:auto;fill-rule:evenodd;font-feature-settings:normal;font-variant-alternates:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-variant-position:normal;image-rendering:auto;isolation:auto;mix-blend-mode:normal;opacity:.1;shape-padding:0;shape-rendering:auto;solid-color:#000000;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-orientation:mixed;text-transform:none;white-space:normal"/>
```

There are several irrelevant variables at the end.

2017-06-22 08:47 UTC, W-Floyd commented
Huh... Maybe I should just redraw it?

On Thu, Jun 22, 2017 at 6:46 PM, Vincent Bermel <notifications@github.com>
wrote:

> *@palob* requested changes on this pull request.
>
> Theres still strange paths, e.g.
>
> <path d="m20 10.586-1.4141 1.4141 2.414 2.414v7.4121l-5.4199 15.174h18.84l-5.4199-15.174v-7.4121l2.414-2.414-1.4141-1.4141-3 3v8.5879l4.582 12.826h-13.164l4.582-12.826v-8.5879zm3.8574 14.414-2.8574 8h8l-2.8574-8z" dominant-baseline="auto" style="color-rendering:auto;color:#000000;dominant-baseline:auto;fill-rule:evenodd;font-feature-settings:normal;font-variant-alternates:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-variant-position:normal;image-rendering:auto;isolation:auto;mix-blend-mode:normal;opacity:.1;shape-padding:0;shape-rendering:auto;solid-color:#000000;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-orientation:mixed;text-transform:none;white-space:normal"/>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/numixproject/numix-core/pull/3735#pullrequestreview-45655464>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALPXlJM7gXt7EIu-VPrvXaZ2VC3emoICks5sGinngaJpZM4Np1gj>
> .
>

2017-06-22 08:49 UTC, palob commented
Yeah, maybe start with a fresh baseplate and paste symbol+shadow in.

2017-06-22 09:42 UTC, W-Floyd commented
I tried that, no luck. I tried re-drawing from scratch, using the template. Still no luck! I am stumped :P

2017-06-22 09:46 UTC, W-Floyd commented
![iconified_steam_icon_344850](https://user-images.githubusercontent.com/11786132/27427740-669e82aa-5783-11e7-8841-cf703d5ee407.png)

2017-06-22 10:49 UTC, W-Floyd commented
I have tentatively removed the extra stuff in the paths. Reoptimizing doesn't change it back, so I'm happy with it.

2017-06-23 03:05 UTC, palob approved these changes

2017-06-23 03:06 UTC, palob approved these changes

2017-07-07 18:44 UTC, merged

2017-07-21 21:10 UTC, palob commented
Fixed #3040