Square icon for zeal.
numixproject/numix-core pull request #3764
Opened 2017-06-21 01:14 UTC by W-Floyd

![iconified_zeal](https://user-images.githubusercontent.com/11786132/27362593-ccb7bbb8-5672-11e7-95b9-8e0b47e16354.png)

2017-06-21 09:16 UTC, palob requested changes
The symbol shadow needs to be shifted 1px to the left.

2017-06-21 09:18 UTC, W-Floyd commented
lol Yup, should have seen that one!

2017-06-21 23:03 UTC, W-Floyd commented
![iconified_zeal](https://user-images.githubusercontent.com/11786132/27410236-9cfb87ee-5729-11e7-8621-cbac1e3841f9.png)

2017-06-22 07:48 UTC, palob approved these changes

2017-07-07 18:41 UTC, merged