add scour optimizations tests
numixproject/numix-core pull request #3920
Opened 2017-09-15 15:17 UTC by bil-elmoussaoui

This PR introduces a new test. The files now must be optimized using scour with those options : 

```shell
scour -i input.svg -o output.svg --disable-style-to-xml --create-groups --renderer-workaround --strip-xml-prolog --enable-comment-stripping --remove-descriptive-elements --enable-id-stripping --protect-ids-noninkscape
```
Those options are the same as the ones described on the wiki. 

The tests, will make sure that the icons and the templates are optimized correctly.

2017-09-15 15:47 UTC, Foggalong requested changes
Needs PEPing. Also, is there a way of testing this before merging like we did with Python?

2017-09-15 15:52 UTC, bil-elmoussaoui commented
Yeah, i will take care of the PEPing. For testing this, you can easily optimize few icons from circle (the icons are ordered alphabetically) so you can take 0ad.svg for example, optimize it using Inkscape or scour, and then just run python3 ./tests/scour.py from the numix-core directory. And you should see that the 0ad icon is optimized correctly 👍 
For now, this shouldn't be merged as the tests verifies all the icons which will take a huge time each time... So we should optimize everything first and then i will switch to verifying the latest icons added on the latest commit or something like that

2017-09-16 08:40 UTC, bil-elmoussaoui commented
I have disabled the scour tests at the moment, will look into this once the optimized icons are on master

2017-11-12 19:22 UTC, bil-elmoussaoui commented
As scour doesn't provide the same output everytime you run it, we will have issues with this kind of tests.
But we can implement our kind of tests like: 
- Verify if there's any comment
- Verify if there's any meta
- Verify if there's an empty group
and we can keep adding tests in order to get the things done

2017-11-13 16:28 UTC, Foggalong commented
@bil-elmoussaoui I suppose that's preferable to nothing at all :) also it'd be good to have tests to make sure in a PR there's the proper changes to the data.json, and that a Circle and Square icon are both added

2017-12-24 13:13 UTC, bil-elmoussaoui commented
This can be closed too, as we can't test if the icons were optimized using scour. The output will be different each time :( 
I might try to implement something manually in the future

2017-12-24 13:13 UTC, closed without merging