Add icon for Age of Mythology
numixproject/numix-core pull request #3959
Opened 2017-11-02 20:33 UTC by matemeszaros

First icon reworked from #3923

![age-of-mythology 192](https://user-images.githubusercontent.com/15245298/32348812-4b06fd2e-c015-11e7-991d-e7f26e7ecf2e.png)

2017-11-02 23:56 UTC, palob requested changes
Only a few small issues:
+ The baseplate gradient is bottom up
+ Can you please use a little bit lighter+desaturated colour for the temple and merge the shadow elements into one path?

2017-11-03 13:11 UTC, palob approved these changes

2017-11-03 13:49 UTC, bil-elmoussaoui commented
I think the icon is really somehow unclear :( maybe something with AOM as a symbol? Otherwise, how we can create an icon for the other versions of AOM ?

2017-11-04 17:46 UTC, matemeszaros commented
@bil-elmoussaoui You may be right - thinking about the first (titans) expansion, what about stylized portaits of the major characters (without the frames)?

| AOM | AOM - Titans |
|:-:|:-:|
| ![aom](https://vignette.wikia.nocookie.net/ageofempires/images/e/e7/ZeusPortrait.png/revision/latest?cb=20160602023355) | ![aom-titans](https://vignette.wikia.nocookie.net/ageofempires/images/7/70/KronosPortrait.png/revision/latest?cb=20160602122801) |

2017-11-10 10:57 UTC, Foggalong approved these changes

2017-11-10 10:57 UTC, merged