Add icon for StarcCraft II
numixproject/numix-core pull request #3965
Opened 2017-11-04 20:05 UTC by matemeszaros

| Original icon | Circle icon | Square icon |
| :-: | :-: | :-: |
| ![924c_starcraft ii 0](https://user-images.githubusercontent.com/15245298/32409001-608c1352-c1a3-11e7-90fb-796dcb0439ad.png) | ![starcraft-2 circle](https://user-images.githubusercontent.com/15245298/32409011-8c7f7e86-c1a3-11e7-836f-02c603ec8860.png) | ![starcraft-2 square](https://user-images.githubusercontent.com/15245298/32409015-94c08676-c1a3-11e7-8bae-4c7ecf890f45.png) |

Reworked from #3923.

2017-11-05 14:16 UTC, palob approved these changes

2017-11-10 11:01 UTC, Foggalong requested changes
In the square icon move the symbol and shadow both up 1px

2017-11-10 16:01 UTC, mrmeszaros commented
@Foggalong: OK, that will mean they will be 2px higher than in circle.

2017-11-11 00:09 UTC, Foggalong commented
That's fine, sometimes the square shape causes the need for extra adjustments :)

2017-11-11 00:09 UTC, Foggalong approved these changes

2017-11-11 00:09 UTC, merged