distributor-logo-plan9 - Icons and entry for Plan 9.
numixproject/numix-core pull request #4018
Opened 2017-12-17 06:22 UTC by W-Floyd

For #2183

![iconified_distributor-logo-plan9](https://user-images.githubusercontent.com/11786132/34077113-644dece4-e346-11e7-8a67-65420d434c47.png)

2017-12-17 11:18 UTC, palob approved these changes

2017-12-23 15:43 UTC, Foggalong requested changes
This looks slightly off balance to me. Try moving the rabbit either 1px or half a px to the left

2017-12-24 07:20 UTC, W-Floyd commented
1/2px

![iconified_distributor-logo-plan9](https://user-images.githubusercontent.com/11786132/34324943-abd4cc94-e8ce-11e7-8a75-624a37468c2d.png)

2017-12-24 11:28 UTC, Foggalong approved these changes

2017-12-24 11:29 UTC, merged