Add CONTRIBUTING.md based on our wiki articles
numixproject/numix-core pull request #4136
Opened 2018-01-03 18:53 UTC by mrmeszaros

Created an initial version of CONTRIBUTING.md mentioned in #4132 

It contains the contents of the more relevant wiki pages.

Definitely needs some brainstorming, to specify what should go there, and what should be only linked to the wiki.

2018-01-03 18:56 UTC, bil-elmoussaoui commented
The file can go under .github btw ;)

2018-01-05 06:31 UTC, mymindstorm commented on .github/CONTRIBUTING.md
> +## Unthemed icons
Quick question: why is this section in CONTRIBUTING.md? I don't see why anyone who is interested in contributing would want this info.

2018-01-05 06:32 UTC, mymindstorm commented on .github/CONTRIBUTING.md
> +## Unthemed icons
Also, you might want to change the README to link to CONTRIBUTING.md and we could drop the wiki page since this pull makes it redundant.

2018-01-05 12:45 UTC, Foggalong requested changes
Keep the contribution guidelines for how to submit pull requests and the procedure to follow. In addition to the "Contribution process" add sections for:

1. **New Icon**: link to the design guidelines, reminder to update `data.json`, and inform that user must include Circle & Square and other themes are optional.
2. **Data File**: an explanation of the structure and how to add/change it. This includes when adding an icon
3. **Python**: we use pycodestyle linting, and basic explanation of @bil-elmoussaoui's validation scripts.

The design guidelines for each theme should stay in the wiki, especially considering they're only going to get longer as new themes are added.

The section on unthemed icons is also irrelivent for the contributing guidelines and should remain a wiki age.

2018-01-06 13:52 UTC, palob commented
Regarding our design guidelines. I'm currently using an Inkscape git build and in the HSL colour notation they changed the ranges for HSL from [0-255,0-255,0-255] to [0-360,0-100,0-100] which afaik is the correct way and how it's done in other graphics applications. This means our baseplate gradient will be 4L instead of 10L as of Inkscape 0.93.

2018-01-06 15:45 UTC, palob commented
That<'s gonna be exhaustive, thanks for your efforts!

2018-02-18 13:35 UTC, Foggalong approved these changes

2018-02-18 13:36 UTC, merged