Icons for Cockatrice
numixproject/numix-core pull request #4189
Opened 2018-02-03 20:44 UTC by palob

https://github.com/Cockatrice/Cockatrice

![index svg](https://user-images.githubusercontent.com/7050624/35771327-5738f8e0-092b-11e8-9850-f8137b3b6a28.png)

![cockatrice-ci](https://user-images.githubusercontent.com/7050624/35771330-5a9c3506-092b-11e8-9199-539d92bd3252.png)
![cockatrice-sq](https://user-images.githubusercontent.com/7050624/35771331-5ac268de-092b-11e8-82aa-45251e3092cf.png)

2018-02-16 22:18 UTC, Foggalong requested changes
Realise that this is just the upstream design, but not merging because it's especially awful. Possibly some iconography involving servers or cards (or both) instead?

2018-02-22 10:06 UTC, palob commented
![cocka](https://user-images.githubusercontent.com/7050624/36532189-5cb5d290-17c0-11e8-921c-c3f67efd5ea0.png)

2018-02-27 12:13 UTC, Foggalong commented
@palob That's good with me :)

2018-02-28 20:00 UTC, Foggalong approved these changes

2018-02-28 20:00 UTC, merged