Icons for quickDocs
numixproject/numix-core pull request #4197
Opened 2018-02-04 00:01 UTC by palob

Fixes #4168 
![quickdocs-ci2](https://user-images.githubusercontent.com/7050624/35773021-e7d7bc9a-0946-11e8-9ce4-2d2f855e9da7.png)
![quickdocs-ci](https://user-images.githubusercontent.com/7050624/35773023-e9617344-0946-11e8-8a8a-210412fa339c.png)

2018-02-16 22:24 UTC, Foggalong requested changes
Even though it's off guidelines I kinda like the look of the striped background. I'm not really sure what the particular relevance is for this icon though since it's about documentation rather than any terminaly stuff?

2018-02-22 08:58 UTC, palob commented
![quickdocs-grid](https://user-images.githubusercontent.com/7050624/36528903-fca2fe72-17b6-11e8-945e-0096b1d02186.png)
![quickdocs-grid2](https://user-images.githubusercontent.com/7050624/36528904-fcc24e30-17b6-11e8-9bf8-adad44658b65.png)
![quickdocs-plain](https://user-images.githubusercontent.com/7050624/36528905-fce15ba4-17b6-11e8-9980-a6f560c3ce26.png)

2018-02-27 12:12 UTC, Foggalong commented
@palob The last one; I do like the baseplate variants but they don't seem applicable to this icon in particular

2018-02-28 19:59 UTC, Foggalong approved these changes

2018-02-28 19:59 UTC, merged