Add icon for Reigns: Her Majesty (Steam)
numixproject/numix-core pull request #4320
Opened 2018-04-19 19:31 UTC by mrmeszaros

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| ![reigns-her-majesty original 96](https://user-images.githubusercontent.com/15245298/38952253-417a35e6-434b-11e8-8511-ee988446d243.png) | ![reigns-her-majesty circle 96](https://user-images.githubusercontent.com/15245298/38952062-af9ad982-434a-11e8-9585-a9b7f8f5ab79.png) | ![reigns-her-majesty square 96](https://user-images.githubusercontent.com/15245298/38952094-cbdf7fbc-434a-11e8-9d78-17283c0bfc10.png) |

The game is a sequel to Reigns (#3726)

2018-04-19 20:01 UTC, palob approved these changes

2018-04-19 21:35 UTC, bilelmoussaoui commented
The game is on Android too nop?

2018-04-20 07:36 UTC, Foggalong submitted a review, later dismissed
[Aye it is](https://play.google.com/store/apps/details?id=com.devolver.reigns2), so the extra info needs adding

2018-04-20 09:24 UTC, mrmeszaros commented
Could not find the `ComponentInfo` in http://activities.tundem.com.

The [prequel](https://play.google.com/store/apps/details?id=com.devolver.reigns) was also missing the android entry - that got added too.

2018-04-20 09:26 UTC, palob approved these changes

2018-04-20 09:44 UTC, bilelmoussaoui requested changes
The second android entry is not a valid one

2018-04-20 09:44 UTC, bilelmoussaoui commented
I will make the right changes in few hours

2018-04-20 14:14 UTC, mrmeszaros commented on data.json
> +            "com.devolver.reigns2"
@bilelmoussaoui I could not find the full `ComponentInfo`

2018-06-19 20:18 UTC, palob commented
@bilelmoussaoui Can you take a look?

2018-07-04 12:59 UTC, Foggalong approved these changes
At  least for now I'm approving this without the extra Android information. It'd be nice to finally get this in the Linux theme, even if the android support has to wait longer.

2018-07-04 12:59 UTC, merged