Icons and entry for Torchlight 2.
numixproject/numix-core pull request #4325
Opened 2018-04-22 03:55 UTC by W-Floyd

Resolves #2255

Baseplate colour was being a bit hard to choose.

![iconified_torchlight-2](https://user-images.githubusercontent.com/11786132/39091301-522c34c2-45bf-11e8-814a-d0294a0c14dd.png)

2018-04-22 09:31 UTC, palob approved these changes

2018-04-24 15:17 UTC, Foggalong requested changes
Rejecting because the light & shadow setup of the source icon contradicts that of our icons, so we can't just copy across the shading from one to the other.

Specifically the original icon has two light source off to the top-left and top-right, affecting the colouring of the symbols. Numix Circle icons are set up with one light source to the top-left (or directly above for Square) which casts an appropriate shadow but doesn't usually change the colours. There are a few exceptions but we generally try and avoid it because lighting works differently in Circle and Square.

Not sure how to resolve it in terms of design changes, but at least the lighting contradiction needs resolving before being merged.

2018-04-24 15:20 UTC, W-Floyd commented
Ah, fair enough. I'll redo the shading at least, then we'll see what else
needs changing.

On Tue, Apr 24, 2018 at 11:17 AM, Joshua H. Fogg <notifications@github.com>
wrote:

> *@Foggalong* requested changes on this pull request.
>
> Rejecting because the light & shadow setup of the source icon contradicts
> that of our icons, so we can't just copy across the shading from one to the
> other.
>
> Specifically the original icon has two light source off to the top-left
> and top-right, affecting the colouring of the symbols. Numix icons are set
> up with one light source to the top-left which casts an appropriate shadow
> but doesn't usually change the colours (there are a few exceptions).
>
> Not sure how to resolve it in terms of design changes, but at least the
> lighting contradiction needs resolving before being merged.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/numixproject/numix-core/pull/4325#pullrequestreview-114834499>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALPXlLlAWQitQiBQPrHEKzDevhwzxi6sks5tr0H6gaJpZM4Tet1F>
> .
>

2018-04-24 15:57 UTC, W-Floyd commented
How about doing away with the shading entirely?

![iconified_torchlight-2](https://user-images.githubusercontent.com/11786132/39199066-9cfd6554-47b6-11e8-8a79-77937a184ccb.png)

2018-04-27 23:30 UTC, palob approved these changes

2018-04-30 17:58 UTC, Foggalong approved these changes

2018-04-30 17:58 UTC, merged