Entry and icons for Ksniffer.
numixproject/numix-core pull request #4326
Opened 2018-04-22 17:13 UTC by W-Floyd

#2294

![iconified_ksniffer](https://user-images.githubusercontent.com/11786132/39097768-e5f19084-462e-11e8-9604-0632f3ba2165.png)

Derived from `preferences-system-search`

2018-04-22 21:31 UTC, palob requested changes
The Square icon has some clip stuff in it. Just deleting it from the code should do it.

2018-04-23 01:51 UTC, W-Floyd commented
I should probably double check `preferences-system-search` then as well.

2018-04-27 21:25 UTC, W-Floyd commented
See #4332 for fixes to `preferences-system-search` as well.

2018-04-27 23:27 UTC, palob approved these changes

2018-04-30 17:57 UTC, merged