Icons for dabradio
numixproject/numix-core pull request #4387
Opened 2018-06-17 17:02 UTC by palob

https://github.com/JvanKatwijk/dabradio

![dabradio](https://user-images.githubusercontent.com/7050624/41510220-f7e009fc-7260-11e8-88d1-bafd67085186.png)
![dabradio-ci](https://user-images.githubusercontent.com/7050624/41510221-f803b686-7260-11e8-9a7f-ee91a341ea20.png)
![dabradio-sq](https://user-images.githubusercontent.com/7050624/41510222-f84047f4-7260-11e8-82d6-5900985b57a7.png)

2018-06-18 22:11 UTC, Foggalong requested changes
I think the yellow cutouts looks a liittle off, even though it works alright in the original. Possibly stick to shadows or just flat colour?

2018-06-19 19:58 UTC, palob commented
Changed to this:

![dabradio2](https://user-images.githubusercontent.com/7050624/41621089-f66942ee-740b-11e8-9f7e-4cfd7be23a74.png)

2018-06-19 20:02 UTC, Foggalong commented
Looks much better :+1:

2018-06-19 20:02 UTC, Foggalong approved these changes

2018-06-19 20:02 UTC, merged