full colour design
numixproject/numix-core pull request #4430
Opened 2018-06-28 21:20 UTC by palob

In favour of  #4426

2018-07-02 14:30 UTC, Foggalong requested changes
That terminal still looks a bit skewy being as wide as that.

2018-07-04 10:59 UTC, palob commented
![kitty-ci](https://user-images.githubusercontent.com/7050624/42273645-08c5e2f6-7f8a-11e8-98bd-46ca747518a6.png)
![kitty-sq](https://user-images.githubusercontent.com/7050624/42273646-08e4cab8-7f8a-11e8-97ab-d3371bd5397b.png)

2018-07-04 12:51 UTC, Foggalong approved these changes

2018-07-04 12:51 UTC, Foggalong commented
Perfect :heart:

2018-07-04 12:51 UTC, merged