Icons for Imaginary Teleprompter
numixproject/numix-core pull request #4434
Opened 2018-07-01 15:11 UTC by palob

https://github.com/ImaginarySense/Teleprompter-Core

![imaginary-teleprompter](https://user-images.githubusercontent.com/7050624/42135879-cf210d76-7d51-11e8-8739-adf0da8a7398.png)
![imaginary-teleprompter-ci](https://user-images.githubusercontent.com/7050624/42135880-cf48b15a-7d51-11e8-9eb3-d6ff3c87bc54.png)
![imaginary-teleprompter-sq](https://user-images.githubusercontent.com/7050624/42135881-cf693fec-7d51-11e8-85ee-a237294a52b0.png)

2018-07-02 14:32 UTC, Foggalong requested changes
Having the 1px outline around the edge gives it a weird feel lighting wise. I'd say increase the width of it or remove it entirely

2018-07-04 10:11 UTC, palob commented
Removed it.

2018-07-04 12:21 UTC, palob commented
Seeing we've got this style cruft there's something new we can craft a script for removing.
I'll experiment with scour and svgcleaner anyway in the course of the Spaure cleaning up issue.

2018-07-04 12:52 UTC, Foggalong approved these changes

2018-07-04 12:52 UTC, merged