Symlinks for adriconf
numixproject/numix-core pull request #4568
Opened 2018-09-04 19:37 UTC by palob

https://github.com/jlHertel/adriconf
![adriconf](https://user-images.githubusercontent.com/7050624/45053624-c57bcb00-b08a-11e8-9594-68a9fc61129d.png)

2018-09-05 00:15 UTC, Foggalong requested changes

2018-09-05 00:15 UTC, Foggalong commented on data.json
>                  "gnome-settings-defaulg-applications",
I think this might be a typo, meaning to say `gnome-settings-default-applications`

2018-09-05 00:15 UTC, Foggalong commented on data.json
> +                "adriconf",
I don't think we should use `application-default-icon` as a root icon for an actual application, has the potential to be misunderstood as a placeholder. Given that it's about graphics drivers the jockey icons might be more appropriate.

2018-09-07 22:03 UTC, palob commented
I'm doing a dedicated one for adriconf

2018-09-11 21:16 UTC, Foggalong approved these changes

2018-09-11 21:16 UTC, merged