Icons for fondo
numixproject/numix-core pull request #4592
Opened 2018-10-01 18:46 UTC by palob

https://github.com/calo001/fondo

![fondo](https://user-images.githubusercontent.com/7050624/46308846-00561d80-c5bb-11e8-90c2-bdab2f38aad5.png)
![fondo-ci](https://user-images.githubusercontent.com/7050624/46308847-00561d80-c5bb-11e8-8240-93e2e682e8a9.png)
![fondo-sq](https://user-images.githubusercontent.com/7050624/46308848-00561d80-c5bb-11e8-94bc-260ed89d3c32.png)

2018-10-02 21:38 UTC, Foggalong commented
Could we manage it without the gradient? Doesn't feel especially numixy as is

2018-10-02 21:38 UTC, Foggalong requested changes
Could we manage it without the gradient? Doesn't feel especially numix-y as is

2018-10-03 08:45 UTC, palob commented
![fondo-ci](https://user-images.githubusercontent.com/7050624/46399961-7bbde900-c6f9-11e8-9edc-f683d5432636.png)
![fondo-sq](https://user-images.githubusercontent.com/7050624/46399963-7bbde900-c6f9-11e8-88d5-3ad8a983c5a0.png)

2018-10-03 13:46 UTC, Foggalong approved these changes

2018-10-03 13:46 UTC, merged