Icons for 4DIAC IDE
numixproject/numix-core pull request #4608
Opened 2018-10-13 20:06 UTC by palob

https://www.eclipse.org/4diac/index.php

![4diac](https://user-images.githubusercontent.com/7050624/46909518-2d4bee00-cf34-11e8-8489-dfdba36c9aa7.png)
![4diac-ci](https://user-images.githubusercontent.com/7050624/46909519-2de48480-cf34-11e8-8fd0-72f7e1f633ed.png)
![4diac-sq](https://user-images.githubusercontent.com/7050624/46909520-2de48480-cf34-11e8-9084-c3dc73ce27f8.png)

2018-12-01 11:08 UTC, Foggalong requested changes
I realise it's in the original icon, but the dark blue being up against the orange of the 4 doesn't look quite right to me. How does it look without it or with that removed? It might be that the current design is still better, not sure

2018-12-01 17:25 UTC, palob commented
Removed it.
![4diac-ci](https://user-images.githubusercontent.com/7050624/49330964-7d3f4c80-f596-11e8-9bd8-264a78a8e0bf.png)
![4diac-sq](https://user-images.githubusercontent.com/7050624/49330965-7d3f4c80-f596-11e8-8764-1a0e7ea5c313.png)

2018-12-04 22:36 UTC, Foggalong commented
Much better, thanks! :)

2018-12-04 22:36 UTC, Foggalong approved these changes

2018-12-04 22:36 UTC, merged