Icons for SpriteIlluminator
numixproject/numix-core pull request #4706
Opened 2019-01-12 22:23 UTC by sprocketc

https://www.codeandweb.com/spriteilluminator

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  ![original](https://user-images.githubusercontent.com/10744960/51079052-2d8d8e00-16c9-11e9-96a7-0c7bad247183.png) |  ![circle](https://user-images.githubusercontent.com/10744960/51081826-13bc6d00-1702-11e9-889d-b3cfbb2e31ae.png) | ![square](https://user-images.githubusercontent.com/10744960/51081829-1f0f9880-1702-11e9-870c-967692f0d1fc.png) |

2019-01-13 00:25 UTC, palob requested changes
Symbol shape/perspective is a bit odd. The lower outer nodes of the "3D cube" should go up a bit.
Maybe the *S* needs to be tweaked a bit then to keep it parallel.

In this case you can transform all nodes into corners. There are some unneeded handles left.

2019-01-13 05:42 UTC, sprocketc commented
I decided to use an orthographic projection (despite the original) to make the symbol look as flat as possible but I forgot to change the upper corner. Should be fixed now.

Unneeded handles removed.
Thumbnails updated.

2019-01-13 10:27 UTC, palob reviewed
Proportions are better now, but the *S* nodes still have got handles.

2019-01-13 20:49 UTC, palob approved these changes

2019-01-24 18:19 UTC, Foggalong approved these changes

2019-01-24 18:19 UTC, merged