New Qt icons. Fixes #4762
numixproject/numix-core pull request #4794
Opened 2019-02-25 21:31 UTC by palob

![qt-circle](https://user-images.githubusercontent.com/7050624/53370070-0aebc780-394d-11e9-9dfb-1b26374ead0b.png)
![qt-square](https://user-images.githubusercontent.com/7050624/53370071-0aebc780-394d-11e9-87f8-4e64e45804c7.png)

2019-02-25 22:43 UTC, bilelmoussaoui commented
Those icons look pretty neat! Great work @palob

2019-02-26 03:30 UTC, Foggalong requested changes
Design wise a massive improvement, great job. Only changes I'd request:

* Switch out the symbol green `#449911` for `#398f43`, it fits in a bit better with the baseplate.
* Is there any way to decrease the size or else go with a different iconograpy for the base symbol on qtconfig? Being a 30px square it looks too big compared to the others there.

2019-02-26 16:47 UTC, palob commented
Pushed
![qt-circle](https://user-images.githubusercontent.com/7050624/53430301-88b3df80-39ee-11e9-9504-390a01c53bee.png)
![qt-square](https://user-images.githubusercontent.com/7050624/53430302-88b3df80-39ee-11e9-9a7e-97b73ae605f6.png)

2019-02-26 21:19 UTC, Foggalong approved these changes

2019-02-26 21:19 UTC, merged