Icons for Dust3D
numixproject/numix-core pull request #4818
Opened 2019-03-15 01:12 UTC by palob

https://github.com/huxingyi/dust3d

![dust3d](https://user-images.githubusercontent.com/7050624/54401379-b32cba80-46c7-11e9-836d-dfb1e457f6e6.png)
![dust3d-ci](https://user-images.githubusercontent.com/7050624/54401380-b32cba80-46c7-11e9-81e9-b09ac20bc0c7.png)
![dust3d-sq](https://user-images.githubusercontent.com/7050624/54401381-b32cba80-46c7-11e9-91bd-1fa94d400ef0.png)

2019-03-15 23:53 UTC, Foggalong requested changes
As much as a camel is a camel, I don't think we should use the symbol we use for Perl for this.

2019-03-16 00:23 UTC, palob commented
Pushed
![dust3d-ci](https://user-images.githubusercontent.com/7050624/54468131-0bc48c00-478a-11e9-8a41-776fb0da4293.png)
![dust3d-sq](https://user-images.githubusercontent.com/7050624/54468132-0bc48c00-478a-11e9-8d2d-d8fa6fada3d4.png)

2019-03-16 10:52 UTC, Foggalong commented
This gave me a giggle when I opened it, love the low poly camel :+1:

2019-03-16 10:52 UTC, Foggalong approved these changes

2019-03-16 10:52 UTC, merged