Icons for Firewatch
numixproject/numix-core pull request #4856
Opened 2019-04-28 07:03 UTC by really-need-an-api-key

Fixes #2991.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| ![f06272a2-055f-11e6-92d0-323674204b12](https://user-images.githubusercontent.com/11636003/56860183-ce136f80-6993-11e9-97cc-9b774fb4c0ea.png) | ![firewatch circle svg](https://user-images.githubusercontent.com/11636003/56860185-d79cd780-6993-11e9-8813-435ca1cf25d8.png) | ![firewatch square2 svg](https://user-images.githubusercontent.com/11636003/56860197-087d0c80-6994-11e9-975c-2613fd5940be.png) |

Symbols are moved 1px down from centered, looks more balanced that way imo.

2019-04-28 09:55 UTC, Foggalong requested changes
I love it, but go with the purple/yellow colour combination in your original comment. It's rare we get an icon which works so well with those combination so we should take the opportunity here!

2019-04-28 19:21 UTC, really-need-an-api-key commented
Done.

| Circle icon | Square icon |
| :-- | :-- |
| ![firewatch 2 circle svg](https://user-images.githubusercontent.com/11636003/56869038-45c8b500-69fb-11e9-9359-afa6db572efa.png) |  ![firewatch 2 square svg](https://user-images.githubusercontent.com/11636003/56869043-4cefc300-69fb-11e9-850f-d20e23b32630.png) |

2019-04-29 18:22 UTC, palob approved these changes

2019-04-29 18:37 UTC, Foggalong approved these changes

2019-04-29 18:37 UTC, merged