Icons for Pace
numixproject/numix-core pull request #4872
Opened 2019-05-24 16:02 UTC by palob

https://gitlab.com/softwareperonista/pace

![pace](https://user-images.githubusercontent.com/7050624/58341205-ffc20e00-7e4d-11e9-9a23-10bd975aa9f0.png)
![pace-ci](https://user-images.githubusercontent.com/7050624/58341207-ffc20e00-7e4d-11e9-81a1-186e8457a50d.png)
![pace-sq](https://user-images.githubusercontent.com/7050624/58341209-ffc20e00-7e4d-11e9-825d-56fccedf2852.png)

2019-05-28 19:15 UTC, Foggalong requested changes
I like the idea of this as a stylistic Pacman icon, but not sold on it for this app because it's seems like a redesign. Did you have any joy with the foot design?

2019-05-28 21:49 UTC, palob commented
I did opt against the foot because it might suggest a relation to GNOME which does not exist.

2019-05-31 08:46 UTC, Foggalong commented
That's actually a very good point, especially with the blue colour. Will merge this and then if upstream take issue with can discuss this in more detail with them then

2019-05-31 08:46 UTC, Foggalong approved these changes

2019-05-31 08:46 UTC, merged