PacmanXG icon update.
numixproject/numix-core pull request #4902
Opened 2019-06-13 16:32 UTC by really-need-an-api-key

Fixes #4766.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| ![pacmanxg original svg](https://user-images.githubusercontent.com/11636003/59450356-5ac1a200-8e09-11e9-9c83-eef04bfbf553.png) | ![pacmanxg circle svg](https://user-images.githubusercontent.com/11636003/59450388-6ca34500-8e09-11e9-809c-4cc481607527.png) | ![pacmanxg square svg](https://user-images.githubusercontent.com/11636003/59450396-6f059f00-8e09-11e9-80d2-c8dd715b1481.png) |

Sorry this took so long.

2019-06-13 22:57 UTC, palob requested changes
Awesome icons but the gradients are reversed.

2019-06-14 14:24 UTC, really-need-an-api-key commented
Whoops. Fixed.

2019-06-15 11:38 UTC, palob approved these changes
Thank you.

2019-06-15 20:00 UTC, Foggalong approved these changes

2019-06-15 20:00 UTC, merged