Icons for qv2ray
numixproject/numix-core pull request #5028
Opened 2020-01-13 20:06 UTC by palob

https://github.com/lhy0403/Qv2ray

![v2ray_1024](https://user-images.githubusercontent.com/7050624/72288088-9430e900-3648-11ea-82c7-1f0890d9e5b1.png)
![v2ray_1024-ci](https://user-images.githubusercontent.com/7050624/72288089-94c97f80-3648-11ea-95ec-ab952b251fa6.png)
![v2ray_1024-sq](https://user-images.githubusercontent.com/7050624/72288090-94c97f80-3648-11ea-91a2-b6427cecd154.png)

2020-01-29 00:20 UTC, creepertron95 commented
@palob The program has a new website and icon just to let you know since you posted this.

Website: https://github.com/Qv2ray/Qv2ray
Icon: 
![qv2ray](https://user-images.githubusercontent.com/53346722/73317048-66c46d80-41fa-11ea-8ffc-2ca73f9d4d7b.png)

The Papirus Icon I worked on for example: [Gv2ray Icon](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/qv2ray.svg)

2020-01-29 12:33 UTC, palob commented
Turns out my reference icon wasn't the old qv2ray one but the current v2ray (which qv2ray is a graphical frontend to) one.

What's the new one supposed to show? That's not even abstract art.

2020-01-29 15:53 UTC, creepertron95 commented
@palob I can't tell what that is or what they were trying to represent on that one.

I thought it was some weird bird wing or whatever.

The icon I put there is the icon they are actually using in their github repo and flathub.

The link you put up seems like they are redirecting it to the one I put up.

2020-02-05 14:56 UTC, Qv2ray-dev commented
I am the Qv2ray maintainer. 

The icon which @palob uploaded a month ago was our design of the old v1 icon, and what's more, that was actually the logo of our upstream, V2ray (https://v2ray.com). Our old logo was a `Q` covering that purple image. As can be found [here](https://github.com/Qv2ray/Qv2ray-v1/blob/master/icons/Qv2ray.png)

However, weeks ago we had published our Qv2ray version 2 and we have changed into a new logo, that is, what you can found at [here](https://github.com/Qv2ray/Qv2ray/blob/master/assets/icons/qv2ray.png)

If anyone wants to use Qv2ray's icon, please use the latter one. Thanks!

2020-02-05 15:00 UTC, DuckSoft commented
This is @DuckSoft from [Qv2ray](https://github.com/Qv2ray). 

Sorry to have you guys confused about those two icons. To clarify, the icon referenced by @palob is the one we used for *old v1 version*, whose *maintenance is stopped* now. We are now working on v2 version branch, and decided to **use the icon referenced by @creepertron95**.

Thank you for your efforts!

2020-02-05 15:01 UTC, Qv2ray-dev commented
And please, the old link https://github.com/lhy0403/Qv2ray is now deprecated, please use https://github.com/Qv2ray/Qv2ray instead, for package Id, please use the `com.github.Qv2ray` only. Thanks

2020-02-05 15:07 UTC, DuckSoft commented
> I thought it was some weird bird wing or whatever.

You are correct. That's a **parrot** in our new icon. Qv2ray is mainly used for breaking the limitation of Great Firewall of China (or virtually any limitations on network). The bird here symbolizes **freedom**.

>![图片](https://user-images.githubusercontent.com/7822648/73853420-c7dbe900-486b-11ea-9b65-946e03cd7b95.png)
> Picture from Bing. Public Domain. Just for Reference. :smile:

2020-02-06 00:06 UTC, palob commented
Thanks for chiming in, will give the new one a shot when I find time.

2020-02-12 22:58 UTC, palob commented
Pushed these new designs

![QV2RAY-ci](https://user-images.githubusercontent.com/7050624/74385287-8317fb00-4df3-11ea-87b5-2ea366bf8f5c.png)
![QV2RAY-sq](https://user-images.githubusercontent.com/7050624/74385289-8317fb00-4df3-11ea-80af-abcb8490eef4.png)

2020-02-16 15:08 UTC, DuckSoft approved these changes
LGTM. Thanks for your great work!

2020-02-16 15:11 UTC, Qv2ray-dev commented
that looks cool dude, thanks for your hard work!

2020-02-16 15:15 UTC, ghost requested changes
Well the old ID if Qv2ray is now removed, so I think it’s unnecessary to put it here.

2020-02-16 15:15 UTC, Qv2ray-dev commented on data.json
> +                "com.github.lhy0403.Qv2ray",
This one can be safely removed FYI

2020-02-22 13:49 UTC, palob commented
Sorry, which line exactly are you referring to?

2020-02-22 13:51 UTC, Qv2ray-dev commented
> Sorry, which line exactly are you referring to?

the `com.github.lhy0403.Qv2ray` one, thanks

2020-03-20 17:45 UTC, Foggalong approved these changes

2020-03-20 17:56 UTC, merged