Icons for Undertale
numixproject/numix-core pull request #5109
Opened 2020-03-21 21:27 UTC by creepertron95

https://store.steampowered.com/app/391540/

![udertale](https://user-images.githubusercontent.com/53346722/77236876-96577c80-6b90-11ea-90c6-443efad11715.png)

![undertale-ci svg](https://user-images.githubusercontent.com/53346722/77236881-9eafb780-6b90-11ea-8882-fcd10cba3319.png)
![undertale-sq svg](https://user-images.githubusercontent.com/53346722/77236884-a1aaa800-6b90-11ea-8392-8d9abf2e014b.png)

2020-03-21 21:45 UTC, palob requested changes
Symbol+shadow can go 1px down for Circle, otherwise fine.

2020-03-22 10:01 UTC, palob approved these changes

2020-03-22 10:02 UTC, palob commented
Now this time the new db entry clashes with ``unciv`` now present in master.

2020-05-31 16:15 UTC, Foggalong approved these changes

2020-05-31 16:29 UTC, merged