Icons for Octodad: Dadliest Catch
numixproject/numix-core pull request #5112
Opened 2020-03-22 18:11 UTC by creepertron95

https://store.steampowered.com/app/224480/
![octodad](https://user-images.githubusercontent.com/53346722/77256825-8e561600-6c3e-11ea-9b88-a093bcce1d79.png)

![octodad-dadliest-catch-ci svg](https://user-images.githubusercontent.com/53346722/77256829-97df7e00-6c3e-11ea-9428-4a2588315cc8.png)
![octodad-dadliest-catch-sq svg](https://user-images.githubusercontent.com/53346722/77256837-a332a980-6c3e-11ea-8bc6-7317d02adc28.png)

2020-03-22 18:13 UTC, creepertron95 commented
There is an android port of this game but, I am not sure if the android theme will worked on later. I would like to see the android theme worked on again though.

2020-03-22 19:31 UTC, palob requested changes
Ideally the eyes would be (maybe slightly edited) ellipses on top of the body path, looks smoother.
Something like this (made it transparent so you can see the remaining head path below).
![ellipse](https://user-images.githubusercontent.com/7050624/77258658-5a99e100-6c7c-11ea-8805-d27c03083322.png)

This it's what's left at the bottom of the symbol.
![path2](https://user-images.githubusercontent.com/7050624/77258662-61c0ef00-6c7c-11ea-9cfd-9ce22cb73e0d.png)


Shadows for the eyes/moustache might be worth a shot.

2020-04-09 07:52 UTC, palob requested changes
Thank you for the fixes. Sorry, my eye shadow idea turns out to be nonsense, it makes the Circle icon look weirdly asymmetrical, will be better without.

There's some SVG cruft again. Could you please remove this?

2020-05-10 21:20 UTC, palob approved these changes

2020-05-31 20:00 UTC, Foggalong approved these changes

2020-05-31 20:00 UTC, merged