Icons for Titan Attacks
numixproject/numix-core pull request #5116
Opened 2020-03-22 23:28 UTC by creepertron95

https://store.steampowered.com/app/203210/

![titan](https://user-images.githubusercontent.com/53346722/77265451-bbb8b900-6c6a-11ea-8cdd-9b8f65ec5a20.png)

![titan-attacks-ci svg](https://user-images.githubusercontent.com/53346722/77265457-c07d6d00-6c6a-11ea-99ca-58b665b45272.png)
![titan-attacks-sq svg](https://user-images.githubusercontent.com/53346722/77265464-c4a98a80-6c6a-11ea-8c5a-b969f065f2c3.png)

2020-03-23 09:39 UTC, palob requested changes
After ``"titan-attacks"`` in data.json a ``:`` is missing.
Usually we try to avoid gradients on new icons but I think it's okay here.

2020-03-23 17:10 UTC, palob approved these changes

2020-06-06 16:31 UTC, Foggalong requested changes
Can we switch up the eyes? Gradients in symbols generally aren't within guidelines and I'm not sure it's adding much to the design here. If you _do_ want some sort of colour change I'd be curious how a two-tone colour change at a specific pixel would look.

2020-06-06 19:55 UTC, palob commented
Aside from that I think the eyes could be brighter.

2020-06-26 16:49 UTC, palob approved these changes

2020-06-28 16:15 UTC, Foggalong approved these changes

2020-06-28 16:16 UTC, merged