Icons for Vertris
numixproject/numix-core pull request #5128
Opened 2020-03-28 00:07 UTC by creepertron95

Fixes #2838

![](https://cloud.githubusercontent.com/assets/10101120/12800031/9d041b8e-ca8f-11e5-8ca5-10feb1a917af.png)

![vertris-ci](https://user-images.githubusercontent.com/53346722/77809536-15035c80-705e-11ea-8ff8-397cc4a598c5.png)
![vertris-sq svg](https://user-images.githubusercontent.com/53346722/77809539-1765b680-705e-11ea-9a37-958d9909185f.png)

2020-03-28 00:11 UTC, palob approved these changes

2020-06-06 16:50 UTC, Foggalong requested changes
I think this is going to need a slightly lighter blue for the baseplate. The contrast with the green on the symbol isn't great.

2020-06-09 09:03 UTC, palob approved these changes

2020-06-14 12:01 UTC, Foggalong approved these changes
Lighter blue definitely worked, also switched in a darker green to improve it that bit further

2020-06-14 12:02 UTC, merged