Icons for Day of the Tentacle Remastered
numixproject/numix-core pull request #5162
Opened 2020-03-31 18:30 UTC by creepertron95

Fixes #3493 

![](https://cloud.githubusercontent.com/assets/649114/20214088/203624d4-a7f3-11e6-824e-155b1c859fb6.png)

![dottr-ci](https://user-images.githubusercontent.com/53346722/78062040-b686f880-7353-11ea-8dd7-8ddcc1edf0b2.png)
![dottr-sq](https://user-images.githubusercontent.com/53346722/78062046-b981e900-7353-11ea-8a5b-7c417cbe4604.png)

2020-03-31 19:23 UTC, palob approved these changes
Splendid! If it turns out too tall, the basal sucker could be reduced to a height of 3px or 2px.

2020-06-06 17:14 UTC, Foggalong requested changes
Yeah this is a bit too tall for me, and symbols on both design could do with moving up 1-2px to counteract the triangle illusion

2020-09-02 20:48 UTC, palob requested changes
Thanks for the shortening. Circle icon can have the symbol 1px more upwards.

2021-04-15 12:29 UTC, palob approved these changes

2021-04-16 21:48 UTC, merged