Flappy bird
numixproject/numix-core pull request #5167
Opened 2020-03-31 23:46 UTC by creepertron95

Fixes #2941

![](https://cloud.githubusercontent.com/assets/13938848/14317800/8f1202c4-fc27-11e5-85b5-5de8813c4146.png)

![flappybird-ci](https://user-images.githubusercontent.com/53346722/78085113-9b31e280-737f-11ea-8fbe-cb935bf13d45.png)
![flappybird-sq](https://user-images.githubusercontent.com/53346722/78085122-a08f2d00-737f-11ea-99a6-006d0bc03ee2.png)

2020-04-01 08:42 UTC, palob requested changes
I think the softer colours used in the original icon might look better.
I'd rather have this black part 2px wide
![2px](https://user-images.githubusercontent.com/7050624/78116958-5486cb80-7405-11ea-9100-5ef9265829a9.png)
and kept the width down here (rightmost nodes shifted 1px to the left)
![1px](https://user-images.githubusercontent.com/7050624/78117011-69fbf580-7405-11ea-9a56-e636904e0c16.png)
![1px-2](https://user-images.githubusercontent.com/7050624/78117025-6cf6e600-7405-11ea-9a6f-2e1a4bb67fdc.png)

2020-09-02 20:50 UTC, palob requested changes
Thanks for the changes. Could we please have the black/grey a bit darker. Looks a tad too washed out at the moment.

2021-04-15 12:31 UTC, palob approved these changes

2021-04-15 12:32 UTC, merged

2021-04-15 14:46 UTC, Foggalong commented
You love to see it :heart: