Icons for Mimo
numixproject/numix-core pull request #5171
Opened 2020-04-03 00:45 UTC by creepertron95

https://play.google.com/store/apps/details?id=com.getmimo

![com getmimo](https://user-images.githubusercontent.com/53346722/78312694-35c62900-751a-11ea-81f2-3d1338f2a1cf.png)

![mimo-ci](https://user-images.githubusercontent.com/53346722/78312703-3d85cd80-751a-11ea-854a-4bb2f9567362.png)
![mimo-sq](https://user-images.githubusercontent.com/53346722/78312709-4080be00-751a-11ea-9b23-4a09083bac7b.png)

Alternative Icon (Based on official iOS icon):
![mimo-alt](https://user-images.githubusercontent.com/53346722/78312726-51c9ca80-751a-11ea-82f7-595fbde5fc4b.png)

2020-04-03 09:04 UTC, palob requested changes
I know it's not technically a doble shadow, it just looks like one but can you alter it (merge & intersect) so that it looks like this (cf. original icon)?
![111](https://user-images.githubusercontent.com/7050624/78343249-d8be8780-759a-11ea-925b-25c7d721c104.png)
Could you please smoothen the cornery nodes of those 2 paths?
![2222](https://user-images.githubusercontent.com/7050624/78343299-ed028480-759a-11ea-8e0f-ffa50d58bcd2.png)

There's some SVG cruft again.

2020-04-09 04:48 UTC, creepertron95 commented
@palob The icon should be fixed now.

2020-04-09 08:04 UTC, palob reviewed
Thanks for the changes, just if you have got some time to spare, could you please fix alignment of the mouth path as seen in the screenshot?

2021-04-15 12:30 UTC, palob approved these changes

2021-04-15 12:31 UTC, merged