Icons for What's inside the box?
numixproject/numix-core pull request #5187
Opened 2020-04-08 00:20 UTC by creepertron95

https://play.google.com/store/apps/details?id=air.com.bartbonte.thebox

![whats-inside-the-box](https://user-images.githubusercontent.com/53346722/78731233-bfa03880-7904-11ea-8157-594e395a5276.png)

![witb-ci](https://user-images.githubusercontent.com/53346722/78731239-c3cc5600-7904-11ea-9125-ca198305317a.png)
![witb-sq](https://user-images.githubusercontent.com/53346722/78731243-c6c74680-7904-11ea-805f-fae8ba340128.png)

2020-04-08 08:03 UTC, palob requested changes
Could you please make the notches 2px wide (or no notches at all, ring darkened in those spots) for better pixel grid alignment?

![Bildschirmfoto vom 2020-04-08 10-00-12](https://user-images.githubusercontent.com/7050624/78759616-2f9fd480-7980-11ea-8c0d-324ecd269825.png)

2020-06-29 08:26 UTC, palob approved these changes

2020-06-29 08:27 UTC, palob commented
db entry has to go before ``whatsie``.

2020-06-29 15:26 UTC, Foggalong approved these changes

2020-06-29 15:26 UTC, merged