Icons for Alien Swarm games
numixproject/numix-core pull request #5334
Opened 2020-06-09 01:45 UTC by creepertron95

Alien Swarm - 

https://store.steampowered.com/app/630/

![alien-swarm](https://user-images.githubusercontent.com/53346722/84096907-bd239300-a9c8-11ea-875d-6b6c6e5ab984.png)

![as-ci](https://user-images.githubusercontent.com/53346722/84096918-c0b71a00-a9c8-11ea-8cf8-e76d1b784580.png)
![as-sq](https://user-images.githubusercontent.com/53346722/84096921-c3197400-a9c8-11ea-9249-c986a5c8eead.png)

---

Alien Swarm: Reactive Drop - 

![alien-swarm-reactive-drop](https://user-images.githubusercontent.com/53346722/84096954-d4fb1700-a9c8-11ea-8c7d-b2a2420231f3.png)

![asrd-ci](https://user-images.githubusercontent.com/53346722/84096960-d88e9e00-a9c8-11ea-81ef-e5f9ed6cfec7.png)
![asrd-sq](https://user-images.githubusercontent.com/53346722/84096965-da586180-a9c8-11ea-9256-d77375f263ed.png)

2020-06-09 09:18 UTC, palob requested changes
The original alien-swarm symbol looks a bit more blueish/livelier. Could we get something like this?
The original reactive drop icon looks slightly brighter.

2020-06-28 18:51 UTC, Foggalong requested changes
I actually quite like the blue of Swarm but agreed, Reactive drop needs to have a brighter symbol

2020-07-20 20:50 UTC, palob approved these changes

2020-09-11 12:44 UTC, Foggalong approved these changes

2020-09-11 12:45 UTC, merged