Redesign Postman Icon
numixproject/numix-core pull request #5353
Opened 2020-06-14 07:13 UTC by creepertron95

Fixes #2443

![](https://user-images.githubusercontent.com/2676579/34940598-17cc20f0-f9be-11e7-8c6d-f0190d502d64.png)

![postman-ci](https://user-images.githubusercontent.com/53346722/84587399-885a7600-ade4-11ea-96e3-46eb3c0b2b82.png)
![postman-sq](https://user-images.githubusercontent.com/53346722/84587401-8abcd000-ade4-11ea-9562-841135d1168d.png)

2020-06-14 08:42 UTC, palob requested changes
It doesn't quite look like their new original icon but it is definitely a lot more interesting.

Could you please fix the shadow though? Right now there are about a gazillion nodes.
![gazillion](https://user-images.githubusercontent.com/7050624/84588935-a9928500-ae2b-11ea-80f2-9638e6544194.png)

Redoing the shadow without duplicating the visor path should do it.

2020-07-18 21:49 UTC, palob approved these changes

2020-07-22 09:51 UTC, Foggalong commented
Gotta love how Inkscape dials it up to 11 when making shadows

2020-07-22 09:51 UTC, Foggalong approved these changes

2020-07-22 09:51 UTC, merged