Icons for A7Xpg
numixproject/numix-core pull request #5364
Opened 2020-06-26 14:39 UTC by creepertron95

http://a7xpg.sourceforge.net/

![a7xpg](https://user-images.githubusercontent.com/53346722/85869097-d8e0b480-b790-11ea-8165-d4dbad2645e5.png)

![a7xpg-ci](https://user-images.githubusercontent.com/53346722/85869104-dc743b80-b790-11ea-8427-bb273c59d190.png)
![a7xpg-sq](https://user-images.githubusercontent.com/53346722/85869114-de3dff00-b790-11ea-829e-5340af8d22e1.png)

2020-06-26 17:14 UTC, palob requested changes
Nice creative design!
Could you please do something like this to counteract the outline rendering issue?
![outlines](https://user-images.githubusercontent.com/7050624/85883396-3270cf80-b7e1-11ea-93b4-8809fcc85817.png)

2020-06-28 19:08 UTC, Foggalong submitted a review, later dismissed

2020-06-28 19:10 UTC, Foggalong commented
I think the baseplate has to be a bit lighter, as is you can't see the baseplate shadow :(

2020-06-28 19:11 UTC, Foggalong requested changes
I think the baseplate has to be a bit lighter, as is you can't see the baseplate shadow :(

2021-08-13 22:16 UTC, merged