Icons for Android ADB File Manager
numixproject/numix-core pull request #5365
Opened 2020-06-26 15:04 UTC by creepertron95

https://github.com/sole/aafm

![aafm](https://user-images.githubusercontent.com/53346722/85871685-61148900-b794-11ea-8563-94756c56efe5.png)

![aafm-ci](https://user-images.githubusercontent.com/53346722/85871624-4e01b900-b794-11ea-9a3e-e12be4a6474e.png)
![aadb-sq](https://user-images.githubusercontent.com/53346722/85871498-198dfd00-b794-11ea-853a-4766ec8036fe.png)

2020-06-26 17:14 UTC, palob approved these changes

2020-06-27 11:25 UTC, Foggalong requested changes
I'm not so certain on using a cut-out here rather than a file manager type symbol. Maybe something [like this](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/thunar.svg) but with the Android head?

As an aside for both designs, any icon which uses a folder symbol also needs sticking in the [Numix Folders](https://github.com/numixproject/numix-folders) repo with alternate designs for each of the folder types we offer.

2020-06-27 15:13 UTC, creepertron95 commented
If that is the case, I can also add in an Android Folder to the base Numix theme as well.

2023-03-04 14:50 UTC, palob commented
I'm merging this as is. Upstream is abandoned so this isn't worth any extra effort.

2023-03-04 14:50 UTC, merged