Icons for Hootsuite
numixproject/numix-core pull request #5367
Opened 2020-06-26 20:10 UTC by creepertron95

Fixes #2504

https://hootsuite.com/

![hootsuite-ci](https://user-images.githubusercontent.com/53346722/85896962-05132a00-b7bf-11ea-9c3f-25ef7faba2d6.png)
![hootsuite-sq](https://user-images.githubusercontent.com/53346722/85896970-06dced80-b7bf-11ea-8d16-09158b670edf.png)

2020-06-26 20:16 UTC, palob requested changes
Circle symbol should be placed at X14, Y10

2020-06-26 20:18 UTC, palob commented
Thanks for fixing those longstanding requests.

2020-06-26 20:28 UTC, creepertron95 commented
Speaking of long-standing requests, Will the Wiznote icon from #4910 be fixed? It's been half a year since the last comment.

2020-07-10 07:35 UTC, palob approved these changes

2020-07-11 10:07 UTC, merged