Icons for Adobe Incopy
numixproject/numix-core pull request #5388
Opened 2020-06-28 23:55 UTC by creepertron95

https://www.adobe.com/products/incopy.html

![Adobe_InCopy_CC_icon](https://user-images.githubusercontent.com/53346722/85961566-eb194900-b970-11ea-8541-1ce4fc6a9b26.png)

![incopy-ci](https://user-images.githubusercontent.com/53346722/85961571-f10f2a00-b970-11ea-9679-d3c61cec2dba.png)
![incopy-sq](https://user-images.githubusercontent.com/53346722/85961573-f2d8ed80-b970-11ea-8647-093c527c9926.png)

2020-06-29 08:03 UTC, palob approved these changes

2020-06-29 08:04 UTC, palob commented
Could you please ungroup the grouped objects? This reduces the filesize.

2020-06-29 15:14 UTC, Foggalong requested changes
ungrouuup

2020-06-29 23:10 UTC, palob approved these changes

2020-06-30 08:53 UTC, Foggalong approved these changes

2020-06-30 08:54 UTC, merged