Icons for Cacher
numixproject/numix-core pull request #5454
Opened 2020-07-04 15:12 UTC by creepertron95

https://www.cacher.io/

![cacher](https://user-images.githubusercontent.com/53346722/86515482-c133ac80-bdde-11ea-9bf4-65cf9338cd2c.png)

![cacher-ci](https://user-images.githubusercontent.com/53346722/86515486-c55fca00-bdde-11ea-8e40-d801f225d790.png)
![cacher-sq](https://user-images.githubusercontent.com/53346722/86515488-c7298d80-bdde-11ea-93a1-7818dafe7d97.png)

2020-07-04 15:34 UTC, Foggalong commented
I've watched that gif on their website loop like five times and was still no clearer as to what their app actually did :joy:

2020-07-04 15:46 UTC, creepertron95 commented
Oh, I accidentally pushed another icon here sorry.

2020-07-04 16:49 UTC, palob requested changes
I think ``<``, ``/`` and ``>`` should be either of the same height or they should be further apart.

2020-07-05 21:44 UTC, palob approved these changes

2020-07-11 09:56 UTC, merged