Icons for Rise of the Tomb Raider
numixproject/numix-core pull request #5489
Opened 2020-07-10 12:53 UTC by BlueManCZ

| Original icon | Circle icon | Square icon |
|-|-|-|
| <img src="https://user-images.githubusercontent.com/17854950/86138784-2ccffe00-baef-11ea-82d5-6262ad8faa54.png" width=128úx> | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/391220/screenshots/

[circ]: https://user-images.githubusercontent.com/17854950/87156390-e3389d80-c2bc-11ea-8361-78d3fa14684e.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/87156401-e6338e00-c2bc-11ea-8516-8d4520cfad60.png "Square"

2020-07-10 20:03 UTC, palob requested changes
Could you please straighten out the jags?
![jags](https://user-images.githubusercontent.com/7050624/87193499-1f89ef00-c2f9-11ea-8b10-5d21316f5a70.png)

The visual change won't be significant unless scaled to 200% and larger or something.

2020-07-10 21:25 UTC, palob approved these changes

2020-07-10 22:46 UTC, creepertron95 commented
For #5404

2020-07-11 10:00 UTC, Foggalong approved these changes

2020-07-11 10:00 UTC, merged