Icons for applications-education
numixproject/numix-core pull request #5525
Opened 2020-07-24 17:57 UTC by creepertron95

![lyricsx-ci](https://user-images.githubusercontent.com/53346722/88420612-c320d800-cdac-11ea-8747-6d3ecca33135.png)
![lyricsx-sq](https://user-images.githubusercontent.com/53346722/88420621-c61bc880-cdac-11ea-88c5-f4c4dfc2e5d8.png)

2020-07-25 09:05 UTC, palob requested changes
Could you please make the **B** 1px narrower and recentre?
![abc](https://user-images.githubusercontent.com/7050624/88453391-bbbe0500-ce66-11ea-9043-61adc5b59dda.png)

Maybe the C could be a bit narrower as well.

2020-09-11 12:51 UTC, Foggalong reviewed
Don't we already have a chalkboard icon like this?

2020-09-15 20:59 UTC, palob commented
Yes, for one of the KDE edu apps I think.

2024-10-28 00:25 UTC, palob approved these changes

2024-10-28 00:26 UTC, merged