Icons for Frostpunk
numixproject/numix-core pull request #5576
Opened 2020-08-26 11:06 UTC by BlueManCZ

| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| <img src="https://www.frostpunkgame.com/wp-content/uploads/2019/10/logo_web.png" width="128"> | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/323190/screenshots/

I used this symbol from the game:

<img src="https://gamepedia.cursecdn.com/frostpunk_gamepedia_en/7/76/FP_Buildings.png?version=ce3f2bdfcfa45f5911be7fb8eba52651">

[orig]: https://www.frostpunkgame.com/wp-content/uploads/2019/10/logo_web.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/91296025-406cad80-e79c-11ea-8168-2a0a89be860a.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/91296308-b244f700-e79c-11ea-95d4-e954afdc59b7.png "Square"

2020-08-26 11:19 UTC, BlueManCZ commented
![A](https://user-images.githubusercontent.com/17854950/91297511-be31b880-e79e-11ea-8991-4f1e637fb134.png) ![B](https://user-images.githubusercontent.com/17854950/91297515-bffb7c00-e79e-11ea-940c-ab281f23cd6e.png)

2020-09-02 20:37 UTC, palob requested changes
The 4 "corners" are slightly misaligned, should be something like this.
![misalign1](https://user-images.githubusercontent.com/7050624/92033827-9c22d200-ed6c-11ea-8649-c09b65b0ab1e.png)
The hammer could benefit from a bit alignment work as well.
![align1](https://user-images.githubusercontent.com/7050624/92033810-93320080-ed6c-11ea-9e17-ec7f1f46107a.png)
You can make it bigger if that helps.

How does it look with the outer ring and the inner plate casting one single shadow onto the baseplate?

2020-09-03 21:39 UTC, palob requested changes
Thanks for the changes.
I think the hammer can sit 1px lower and there are some unneeded nodes inside the symbol shadow left.

2020-09-06 13:46 UTC, Foggalong approved these changes

2020-09-06 13:47 UTC, merged