Add icons for Lords of Waterdeep. Fixes #5508.
numixproject/numix-core pull request #5710
Opened 2021-03-21 08:18 UTC by really-need-an-api-key

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  ![original](https://user-images.githubusercontent.com/11636003/111898403-19bae080-8a26-11eb-92f8-6b9da61bb47f.jpg) |  ![circle](https://user-images.githubusercontent.com/11636003/111898413-29d2c000-8a26-11eb-9eb2-d76ddedf2f49.png) | ![square](https://user-images.githubusercontent.com/11636003/111898415-39ea9f80-8a26-11eb-9ec9-1e846f5a36b2.png) |

2021-03-25 22:43 UTC, palob requested changes
This is something which applies to all your recent PRs including those I had alredy approved of:
Inkscape 1.0 changed the L range of the HSL colour notation to the more common 0...100 (replacing 0...255).
This means that the Numix baseplate gradient should only encompass a range of 4L (instead of the 10L when using pre 1.0 Inkscape).

2021-03-28 18:20 UTC, really-need-an-api-key commented
I didn't realize. I'll go through them again.

2021-03-28 18:29 UTC, really-need-an-api-key commented
![circle-lords-of-waterdeep](https://user-images.githubusercontent.com/11636003/112763325-495c8080-9004-11eb-9216-d4b7c11b217d.png)
![square-lords-of-waterdeep](https://user-images.githubusercontent.com/11636003/112763327-4b264400-9004-11eb-8548-dd720c8a0903.png)

2021-04-02 20:04 UTC, palob approved these changes

2021-04-14 04:31 UTC, merged